name: Build

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 🧹 Lint
        run: cargo clippy -D

      - name: 🧪 Test
        run: cargo test -- --test-threads=1
